/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#E26894",
        primaryDark: "#A04A69",
        red: {
          50: "#FCF0F4",
          100: "#F6D0DE",
          200: "#F2BACE",
          300: "#EC9AB7",
          400: "#E886A9",
          500: "#E26894",
          600: "#CD5F87",
          700: "#A04A69",
          800: "#7C3951",
          900: "#572C3E", 
        },
        grey: {
          50: "#EFEFEF",
          100: "#CCCCCC",
          200: "#B4B4B4",
          300: "#929292",
          400: "#7D7D7D",
          500: "#5C5C5C",
          600: "#545454",
          700: "#414141",
          800: "#333333",
          900: "#272727",
        },
        error: "#DE3730"
      },
      textVariant: {
        "bodySmallRegular": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Regular",
          fontSize: 12,
          lineHeight: 16,
        },
        "labelMediumMedium": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Medium",
          fontSize: 12,
          lineHeight: 16,
          letterSpacing: 0.5,
        },
        "titleLargeMedium": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "SemiBold",
          fontSize: 22,
          lineHeight: 28,
        },
        "title3Regular": {
          fontFamily: "SF Pro",
          fontWeight: "Regular",
          fontSize: 20,
          lineHeight: 25,
          letterSpacing: -0.4,
        },
        "subtitle2SemiBold": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "SemiBold",
          fontSize: 14,
          letterSpacing: 0.1,
        },
        "labelMediumRegular": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Regular",
          fontSize: 12,
          lineHeight: 16,
          letterSpacing: 0.5,
        },
        "captionRegular": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Regular",
          fontSize: 12,
          letterSpacing: 0.4,
        },
        "labelSmallRegular": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Regular",
          fontSize: 11,
          lineHeight: 16,
          letterSpacing: 0.5,
        },
        "bodyLargeRegular": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Regular",
          fontSize: 16,
          lineHeight: 24,
          letterSpacing: 0.5,
        },
        "m3TitleMedium": {
          fontFamily: "Roboto",
          fontWeight: "Medium",
          fontSize: 16,
          lineHeight: 24,
          letterSpacing: 0.15,
        },
        "labelLarge": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Medium",
          fontSize: 14,
          lineHeight: 20,
          letterSpacing: 0.1,
        },
        "headlineSmall": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Regular",
          fontSize: 24,
          lineHeight: 32,
        },
        "headlineLarge": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Regular",
          fontSize: 32,
          lineHeight: 40,
        },
        "displaySmall": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Regular",
          fontSize: 36,
          lineHeight: 44,
        },
        "labelMedium": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Medium",
          fontSize: 12,
          lineHeight: 16,
          letterSpacing: 0,
        },
        "labelSmall": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Medium",
          fontSize: 11,
          lineHeight: 16,
          letterSpacing: 0,
        },
        "titleSmall": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "SemiBold",
          fontSize: 14,
          lineHeight: 20,
          letterSpacing: 0.1,
        },
        "titleLarge": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "SemiBold",
          fontSize: 22,
          lineHeight: 28,
        },
        "titleMedium": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "SemiBold",
          fontSize: 16,
          lineHeight: 24,
          letterSpacing: 0,
        },
        "bodyMediumSemiBold": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "SemiBold",
          fontSize: 14,
          lineHeight: 20,
          letterSpacing: 0,
        },
        "bodyLarge": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Regular",
          fontSize: 16,
          lineHeight: 24,
          letterSpacing: 0.5,
        },
        "bodySmall": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Regular",
          fontSize: 12,
          lineHeight: 16,
        },
        "bodyMedium": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "Regular",
          fontSize: 14,
          lineHeight: 20,
          letterSpacing: 0,
        },
        "headlineMedium": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "SemiBold",
          fontSize: 28,
          lineHeight: 36,
        },
        "displayMedium": {
          fontFamily: "Be Vietnam Pro",
          fontWeight: "SemiBold",
          fontSize: 45,
          lineHeight: 52,
        },
      },
    },
    plugins: [],
  }
}