name: Release APK

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Access workspace 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # - name: Set up Java SDK
    #   uses: actions/setup-java@v4
    #   with:
    #     distribution: 'temurin'
    #     java-version: '22'

    # - name: Set up Android SDK
    #   uses: android-actions/setup-android@v3
      
    # - name: Set up pnpm
    #   uses: pnpm/action-setup@v4
    #   with: 
    #     version: 'latest'

    # - name: Install dependencies without updating lockfile
    #   run: pnpm i --frozen-lockfile

    # - name: Generate 'android' folder
    #   run: pnpm expo run:android
    #   continue-on-error: true

    # - name: Set Gradle version to 8.8
    #   run: |
    #     sed -i 's|distributionUrl=.*|distributionUrl=https\://services.gradle.org/distributions/gradle-8.8-all.zip|' \
    #     "$PWD/android/gradle/wrapper/gradle-wrapper.properties"

    # - name: Build APK
    #   run: ./gradlew assembleRelease
    #   working-directory: android

    # - name: Sign APK
    #   uses: r0adkll/sign-android-release@v1
    #   with:
    #     # releaseDirectory: android/app/build/outputs/apk/release
    #     releaseDirectory: .
    #     signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
    #     alias: ${{ secrets.ALIAS }}
    #     keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
    #     keyPassword: ${{ secrets.KEY_PASSWORD }}
    #   env:
    #       # override default build-tools version (33.0.0) -- optional
    #       BUILD_TOOLS_VERSION: "34.0.0"

    - name: Get begin-sha (Last commit in the previous release)
      id: begin-sha
      run: echo "::set-output name=begin-sha::$(git rev-list --tags --max-count=1)"

    - name: Get commit messages between releases
      id: commit-messages
      run: |
        echo -n "\"" >> commit-messages.txt
        git log ${{ steps.begin-sha.outputs.begin-sha }}..HEAD --pretty=format:"%h: %s" | awk '{printf "%s\\n", $0}' ORS='' >> commit-messages.txt
        echo -n "\"" >> commit-messages.txt
        echo "::set-output name=body-messages::$(cat commit-messages.txt)"

    - name: Echo data in commit-messages.txt
      run: cat commit-messages.txt

    - name: Assign to env variable
      run: echo "body-messages=$(cat commit-messages.txt)" >> $GITHUB_ENV

    - name: Upload APK
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.SECRET_TOKEN }}
        # file: android/app/build/outputs/apk/release/app-release-signed.apk
        file: app-release.apk
        asset_name: Demo.apk
        tag: 1.0.4
        overwrite: true
        # body: ${{ env.body-messages }}
        body: "459c108: Pump ver to 1.0.4\na85c2f2: Use body msg\nde12381: Append not replace\nfc91e9f: Fix output\ncd6a006: Merge branch 'main' of https://github.com/ducviet5138/native\n2f8a30d: Add abc \n3dac50d: Update main.yml\n5b97756: Skip unused package\n0154528: Update main.yml\n80afdaf: Update main.yml\n783b83f: Set output\nd9234e8: Fix msg\n1e3e6fb: Fix msg\nf2da379: Fix msg\ne583706: Merge branch 'main' of https://github.com/ducviet5138/native\n596506f: Fix\n5645d27: Update main.yml\n69e383d: with \n\n46d9798: Without \n\n1e625ed: Hahahha\nb3ca209: New\na4d0b3a: Fix\n88242a7: Moas\n51564bf: Echo\n00dab54: Change method\n55aa803: Test\na32dbd7: Add depth\n652f376: :)))))))\nd8d6bce: cat to GITHUB_ENV.body_message\n7a979e6: Alo\n16efeee: Fix\nf112cf5: Đại đi\n471f5f7: ....\nc3a517a: Hard text of begin-sha\n853701d: Print\n66a9f99: Rm end-sha\n3325b42: Hmmm\ne3aff70: Qua mot\n"
