name: Release APK

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Access workspace 
      uses: actions/checkout@v4

    - name: Set up Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with: 
        version: 'latest'

    - name: Install dependencies without updating lockfile
      run: pnpm i --frozen-lockfile

    # - name: Generate 'android' folder
    #   run: pnpm expo run:android
    #   continue-on-error: true

    # - name: Set Gradle version to 8.8
    #   run: |
    #     sed -i 's|distributionUrl=.*|distributionUrl=https\://services.gradle.org/distributions/gradle-8.8-all.zip|' \
    #     "$PWD/android/gradle/wrapper/gradle-wrapper.properties"

    # - name: Build APK
    #   run: ./gradlew assembleRelease
    #   working-directory: android

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        # releaseDirectory: android/app/build/outputs/apk/release
        releaseDirectory: .
        signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"
    
    - name: Find Previous Tag
      id: prev_tag
      run: echo "PREV_TAG=$(git describe --tags --abbrev=0 HEAD^)" >> $GITHUB_ENV

    - name: Generate Release Body
      id: generate_body
      run: |
        echo "RELEASE_BODY=$(git log ${{ env.PREV_TAG }}..HEAD --pretty=format:'%h %s' --reverse)" >> $GITHUB_ENV
        echo "::set-output name=body::$(echo -e "${{ env.RELEASE_BODY }}")"
    
    - name: Echo prev tag
      run: echo ${{ env.PREV_TAG }}

    - name: Echo release body
      run: echo ${{ env.RELEASE_BODY }}

    - name: Upload APK
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.SECRET_TOKEN }}
        # file: android/app/build/outputs/apk/release/app-release-signed.apk
        file: app-release-signed.apk
        asset_name: Demo.apk
        tag: 1.0.1
        overwrite: true
        body: ${{ env.RELEASE_BODY }}
