name: Release APK

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Access workspace 
      uses: actions/checkout@v4

    - name: Set up Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with: 
        version: 'latest'

    - name: Install dependencies without updating lockfile
      run: pnpm i --frozen-lockfile

    - name: Generate 'android' folder
      run: pnpm expo run:android
