name: Release APK

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Access workspace 
      uses: actions/checkout@v4

    - name: Set up Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with: 
        version: 'latest'

    - name: Install dependencies without updating lockfile
      run: pnpm i --frozen-lockfile

    - name: Generate 'android' folder
      run: pnpm expo run:android
      continue-on-error: true

    - name: Get current directory and assign to CURRENT_DIR
      run: echo "CURRENT_DIR=$PWD" >> $GITHUB_ENV

    - name: Move signed key to android folder
      run: mv ./my-upload-key.keystore ./android/app/my-upload-key.keystore
    
    # Ref: https://github.com/orgs/community/discussions/24928
    - name: Modify gradle.properties
      run: |
        cat << EOF >> ./android/gradle.properties
        ${{ secrets.GRADLE_PROPERTIES }}
        EOF

    - name: Write out data of gradle-wrapper.properties
      run: cat ${{ env.CURRENT_DIR }}/android/gradle/wrapper/gradle-wrapper.properties
    
    - name: Modify gradle-wrapper.properties
      run: |
        sed -i '' 's|distributionUrl=.*|distributionUrl=https\\://services.gradle.org/distributions/gradle-8.8-all.zip|'
        ${{ env.CURRENT_DIR }}/android/gradle/wrapper/gradle-wrapper.properties

    - name: Generate AAB release
      run: pnpm react-native build-android --mode=release