name: Release APK

on: 
  push:
    branches:
      - 'main'
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Access workspace 
      uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Set up Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with: 
        version: 'latest'

    - name: Install dependencies without updating lockfile
      run: pnpm i --frozen-lockfile

    # - name: Generate 'android' folder
    #   run: pnpm expo run:android
    #   continue-on-error: true

    # - name: Set Gradle version to 8.8
    #   run: |
    #     sed -i 's|distributionUrl=.*|distributionUrl=https\://services.gradle.org/distributions/gradle-8.8-all.zip|' \
    #     "$PWD/android/gradle/wrapper/gradle-wrapper.properties"

    # - name: Build APK
    #   run: ./gradlew assembleRelease
    #   working-directory: android

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        # releaseDirectory: android/app/build/outputs/apk/release
        releaseDirectory: .
        signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"

    - name: Get begin-sha (Last commit in the previous release)
      id: begin-sha
      run: echo "::set-output name=begin-sha::$(git rev-list --tags --max-count=1)"

    - name: Get commit messages between releases
      id: commit-messages
      run: |
        git log 7d601a7a0b010dd68f9f0ca19b1ea04af40bee5f..HEAD --pretty=format:"%h: %s" | awk '{printf "%s\\n", $0}' ORS='' >> commit-messages.txt
        echo "::set-output name=body-messages::$(cat commit-messages.txt)"

    - name: Echo data in commit-messages.txt
      run: cat commit-messages.txt

    - name: Upload APK
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.SECRET_TOKEN }}
        # file: android/app/build/outputs/apk/release/app-release-signed.apk
        file: app-release-signed.apk
        asset_name: Demo.apk
        tag: 1.0.3
        overwrite: true
        body: ${{ steps.commit-messages.outputs.body-messages }}
