name: Release APK

on: 
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Access workspace 
      uses: actions/checkout@v4

    - name: Set up Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'
