name: Release APK

on: 
  push:
    branches:
      - 'main'
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Access workspace 
      uses: actions/checkout@v4

    - name: Set up Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with: 
        version: 'latest'

    - name: Install dependencies without updating lockfile
      run: pnpm i --frozen-lockfile

    # - name: Generate 'android' folder
    #   run: pnpm expo run:android
    #   continue-on-error: true

    # - name: Set Gradle version to 8.8
    #   run: |
    #     sed -i 's|distributionUrl=.*|distributionUrl=https\://services.gradle.org/distributions/gradle-8.8-all.zip|' \
    #     "$PWD/android/gradle/wrapper/gradle-wrapper.properties"

    # - name: Build APK
    #   run: ./gradlew assembleRelease
    #   working-directory: android

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        # releaseDirectory: android/app/build/outputs/apk/release
        releaseDirectory: .
        signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"
    
    # Get lastest commit in previous tag
    - name: Get lastest commit in previous tag
      id: commit-messages
      run: |
        git fetch --tags
        git log $(git describe --tags --abbrev=0)..HEAD --oneline > commit_messages.txt
        echo "::set-output name=commit_messages::$(cat commit_messages.txt)"

    # Print it to the console
    - name: Print commit messages
      run: echo ${{ steps.commit-messages.outputs.commit_messages }}

    - name: Upload APK
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.SECRET_TOKEN }}
        # file: android/app/build/outputs/apk/release/app-release-signed.apk
        file: app-release-signed.apk
        asset_name: Demo.apk
        tag: 1.0.1
        overwrite: true
        body: ${{ steps.commit-messages.outputs.commit_messages }}
