name: Release APK

on: 
  push:
    branches:
      - 'main'

jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Access workspace 
      uses: actions/checkout@v4

    - name: Set up Java SDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with: 
        version: 'latest'

    - name: Install dependencies without updating lockfile
      run: pnpm i --frozen-lockfile

    - name: Generate 'android' folder
      run: pnpm expo run:android
      continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
    - name: Access workspace 
      uses: actions/checkout@v4
      
    - name: Copy prepared file to its folder
      run: cp -a ./android-override/* ./android/
    
    # Ref: https://github.com/orgs/community/discussions/24928
    - name: Append gradle.properties
      run: |
        cat << EOF >> ./android/gradle.properties
        ${{ secrets.GRADLE_PROPERTIES }}
        EOF
    
    - name: Generate AAB release
      run: pnpm react-native build-android --mode=release

    - name: Build APK from AAB
      run: cd android && ./gradlew bundleRelease

    - name: Run ls to check APK
      run: cd ./app/build/outputs/apk && ls